---
# Copyright 2016 LSD/UFCG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install monasca-notification required pip packages (venv)
  pip:
    name: "{{ item }}"
    virtualenv: "/opt/venvs/monasca-notification"
  with_items:
    - "mysql-python"
    - "file://{{ monasca_common_tarball.stdout }}"
    - "file://{{ monasca_statsd_tarball.stdout }}"
  tags:
    - monasca-notification-pip-packages
    - monasca-install-notification

- name: Create monasca-notification tarball
  command: "/opt/venvs/monasca-notification/bin/python setup.py sdist"
  args:
    chdir: "/opt/cloned-repos/monasca-notification"
  register: notification_result
  changed_when: "notification_result.rc == 0"
  tags:
    - monasca-notification-tarball
    - monasca-install-notification

- name: Get tarball file name
  shell: "ls -td /opt/cloned-repos/monasca-notification/dist/monasca-notification-*.tar.gz | head -1"
  register: tarball
  changed_when: false
  tags:
    - monasca-notification-install
    - monasca-install-notification

- name: Install monasca-notification
  pip:
    name: "file://{{ tarball.stdout }}"
    virtualenv: "/opt/venvs/monasca-notification"
  tags:
    - monasca-notification-install
    - monasca-install-notification

- name: Drop monasca-notification Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "monasca-notification/monasca-notification.service.j2"
      dest: "/etc/systemd/system/monasca-notification.service"
      owner: "root"
      group: "root"
      mode: "0644"
    - src: "monasca-notification/notification.yaml.j2"
      dest: "/etc/monasca/notification.yaml"
      owner: "mon-notification"
      group: "monasca"
      mode: "0660"
  tags:
    - monasca-notification-config
    - monasca-install-notification

- name: Ensure monasca-notification launches on boot
  service:
    name: "monasca-notification"
    enabled: "yes"
  tags:
    - monasca-monasca-notification

- name: Restart monasca-notification
  service:
    name: "monasca-notification"
    state: "restarted"
  tags:
    - monasca-notification-restart
    - monasca-install-notification
